### ISSUE TITLE
Bug in Seq-InSite.sh

### ISSUE THREAD

**Issue by AjSiciliano** [lucian-ilie/Seq-InSite#1]
Hello, 

In Seq-InSite.sh, line 20 should be changed to:

`python Utils/fastaToFiles.py $DATASET_FILE $fastaDir`

from:

`python Utils/fastaToFile.py $DATASET_FILE $fastaDir`

In Seq-InSite.sh, line 30 should be changed to:

`python Architectures/predict_ENS.py $DATASET_FILE $embd $t5Embd $output`

from:

`python Architecture/predict_ENS.py $DATASET_FILE $embd $t5Embd $output`

**Comment by mohsenh17** [comment]
thank you. updated
